language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t trevordavid/docker-react -f Dockerfile.dev .

script:
  - docker run trevordavid/docker-react npm run test -- --coverage